### ISSUE TITLE
Package as flatpak and distribute on flathub

### ISSUE THREAD

**Issue by unpinned** [FyraLabs/skiff-desktop#1]
Would be great if we can install this application from flathub.

**Comment by lleyton** [comment]
Just pushed a commit which should get the Flatpak manifests working.
https://github.com/FyraLabs/skiff-desktop/commit/039ca68d00d17e1abea6e933edca0048fa0c26c3

I'll probably have to submit it to Flathub a bit later as I'm pretty busy. However, if someone wants to do that on our behalf, I give them permission for that :)

**Comment by unpinned** [comment]
someone submitted it to flathub :eyes: https://flathub.org/apps/io.github.dhadder3.SkiffDesktopAdw should the issue be closed?

**Comment by yochananmarqos** [comment]
@dhadder3 Maybe create a PR?

@lleyton The [fork](https://github.com/dhadder3/skiffdesktop-adw) also uses `libadwaita` instead of `libhelium`. :grin:

**Comment by dhadder3** [comment]
> @dhadder3 Maybe create a PR?
> 
> @lleyton The [fork](https://github.com/dhadder3/skiffdesktop-adw) also uses `libadwaita` instead of `libhelium`. 😁

Absolutely, I can make a PR soon. I wasn’t sure whether or not @lleyton wanted to keep `libhelium`

**Comment by korewaChino** [comment]
> > @dhadder3 Maybe create a PR?
> > @lleyton The [fork](https://github.com/dhadder3/skiffdesktop-adw) also uses `libadwaita` instead of `libhelium`. 😁
> 
> Absolutely, I can make a PR soon. I wasn’t sure whether or not @lleyton wanted to keep `libhelium`

We literally make Helium.

Of course we want to keep it, we made the thing.

Question though: why Adwaita instead?

**Comment by nothingneko** [comment]
Dylan, I'm sorry about the hostility. Cappy, you're taking this really poorly and I need you to take a step back. I would like to wait for Lea’s input before moving forward. I have this in front of her and we’ll have updates soon!

**Comment by dhadder3** [comment]
No worries! I may have published it to Flathub a bit hastily, sorry about that! I look forward to hearing from Lea.

**Comment by yochananmarqos** [comment]
@korewaChino 

> We make Helium

Ah, I didn't know that.

> why Adwaita instead?

For one thing, building this project using `libhelium` does not load the UI running it. The fork  with `libadwaita` works fine.

**Comment by nothingneko** [comment]
> @korewaChino 
> 
> 
> 
> > We make Helium
> 
> 
> 
> Ah, I didn't know that.
> 
> 
> 
> > why Adwaita instead?
> 
> 
> 
> For one thing, building this project using `libhelium` does not load the UI running it. The fork  with `libadwaita` works fine.
> 
>  

What do you mean?

**Comment by yochananmarqos** [comment]
@nothingneko The GUI launches, however there's just a perpetual spinning circle in the middle.

**Comment by nothingneko** [comment]
> @nothingneko The GUI launches, however there's just a perpetual spinning circle in the middle.

Could I see a screenshot?

**Comment by yochananmarqos** [comment]
![image](https://github.com/FyraLabs/skiff-desktop/assets/5437803/96e3b6cc-236f-4bb3-aae6-c720d80d2756)

**Comment by dhadder3** [comment]
This issue should have been fixed with this merge https://github.com/FyraLabs/skiff-desktop/commit/0155479c5a323036c2b1dcff2f0e56bcf67f358c
Try fully rebuilding if you haven't!

**Comment by yochananmarqos** [comment]
@dhadder3 Yes, that resolved the issue.

**Comment by lleyton** [comment]
Heya, sorry for the delayed response. Here are my thoughts on the matter:
- Ideally, only one app should be on Flathub to prevent user confusion. I personally believe it makes sense for ours to be canonical, considering that we're upstream. The Skiff team has also showed interest in adopting the app into their org, so that's another factor.
- Considering the above, one of the codebases have to go. We have a bias towards libhelium, as it's something we built, and have our own design opinions implemented through the library. However, I do acknowledge that because libhelium is still in rapid development (don't let the 1.x.x version fool you), so it might not be ideal for users. On the contrary, an app like this allows us to test libhelium in the wild (outside of the tauOS ecosystem) and would be useful for improving the library.
- If we do switch over the current Flathub app to the libhelium codebase, I wonder if that switch would cause user confusion/frustration. Currently the app has 153 installs on Flathub as I'm writing this. However, might be worth it to bite that bullet now, if we do decide to switch to libhelium down the line.

I'm honestly not 100% sure what the correct answers are here, and I would appreciate your input. I'm currently on the side of taking over the current Flathub app (or maybe giving ownership to Skiff) and using the libhelium codebase.

**Comment by lleyton** [comment]
On another note, I'm sorry that the conversation went the way it did before. It was not our intention to bash you or your efforts. While we might have felt hurt about replacing libhelium with libadwaita, I understand why you did, and it was not appropriate for us to respond in that way. I want to be clear that I appreciate your efforts, I hope we can move forward together.

**Comment by dhadder3** [comment]
> Heya, sorry for the delayed response. Here are my thoughts on the matter:
> 
>     * Ideally, only one app should be on Flathub to prevent user confusion. I personally believe it makes sense for ours to be canonical, considering that we're upstream. The Skiff team has also showed interest in adopting the app into their org, so that's another factor.
> 
>     * Considering the above, one of the codebases have to go. We have a bias towards libhelium, as it's something we built, and have our own design opinions implemented through the library. However, I do acknowledge that because libhelium is still in rapid development (don't let the 1.x.x version fool you), so it might not be ideal for users. On the contrary, an app like this allows us to test libhelium in the wild (outside of the tauOS ecosystem) and would be useful for improving the library.
> 
>     * If we do switch over the current Flathub app to the libhelium codebase, I wonder if that switch would cause user confusion/frustration. Currently the app has 153 installs on Flathub as I'm writing this. However, might be worth it to bite that bullet now, if we do decide to switch to libhelium down the line.
> 
> 
> I'm honestly not 100% sure what the correct answers are here, and I would appreciate your input. I'm currently on the side of taking over the current Flathub app (or maybe giving ownership to Skiff) and using the libhelium codebase.

I fully agree. The current app-id for the fork on Flathub contains `SkiffDesktopAdw` (since I was originally thinking to update the Flathub page to clearly differentiate from the libhelium repo if there were 2 pages) this could cause confusion. A possible option could be to EOL the libadwaita fork, request it to be archived, and republish the libhelium project on Flathub. I appreciate it and apologize for any frustration caused!

**Comment by lleyton** [comment]
That works with me, shall I submit the libhelium version to Flathub first? Or, do you want to EOL your fork first?

**Comment by dhadder3** [comment]
> That works with me, shall I submit the libhelium version to Flathub first? Or, do you want to EOL your fork first?

If you could submit the libhelium version, I could add links to the new Flathub page and then EOL the fork, unless there are any concerns

**Comment by nothingneko** [comment]
We're also gonna have to submit the platform to Flathub. I'm not sure if there are any notable differences between submitting an app and submitting a platform so we'll have to look into it.

**Comment by lleyton** [comment]
https://github.com/flathub/flathub/pull/4756

here we go :p

**Comment by yochananmarqos** [comment]
Well, while we're on the subject of packaging, here's a preliminary [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/blob/master/skiff-desktop/PKGBUILD). I currently use Ferdium for web-based applications like this, so I'm not sure if I'll bother adding it to the AUR or not.

**Comment by lleyton** [comment]
I personally don't use arch, but I'd love to see an AUR package if someone is up for it.
